Fix: Package spotlight_data/assets to fix missing spotlight_behavior_clip.npz
The tutorial https://neuromechfly.org/tutorials/2_replaying_experimental_recordings/ currently results in an error

FileNotFoundError: [Errno 2] No such file or directory: '.venv/lib/python3.12/site-packages/flygym_demo/spotlight_data/assets/spotlight_behavior_clip.npz'

This change adds spotlight_behavior_clip.npz to the build


## Before

```bash
uv build
python -m zipfile --list dist/flygym-2.0.0-py3-none-any.whl | grep .npz
# Nothing

# Files present before
python -m zipfile --list dist/flygym-2.0.0-py3-none-any.whl | wc -l
111
du -sh ./dist/flygym-2.0.0-py3-none-any.whl
8.4M	./dist/flygym-2.0.0-py3-none-any.whl
```

## After

```bash
uv build
python -m zipfile --list dist/flygym-2.0.0-py3-none-any.whl | grep .npz
flygym_demo/spotlight_data/assets/spotlight_behavior_clip.npz 2026-04-16 06:25:14       528912

# Ensuring Only 1 file added
python -m zipfile --list dist/flygym-2.0.0-py3-none-any.whl | wc -l
112
du -sh ./dist/flygym-2.0.0-py3-none-any.whl
8.9M	./dist/flygym-2.0.0-py3-none-any.whl
```